In [1]:
import datetime
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from numba import jit
from scipy.spatial.distance import pdist, squareform
from scipy.optimize import root_scalar, curve_fit
from pynndescent import NNDescent
from scipy.sparse import csr_matrix
from sklearn.decomposition import PCA

In [2]:
def exp_k(dists, sigma):
    return np.exp(- (dists - dists[0]) / sigma).sum()

In [3]:
def find_sigma(d, k, lower_bound=1e-6, upper_bound=1e6):
    return root_scalar(
        lambda s: exp_k(d, s) - np.log2(k),
        bracket=(lower_bound, upper_bound)
    ).root

In [4]:
def p_ij_sym(x, k, verbose=False):
    num_pts = x.shape[0]
    if verbose:
        print('Indexing')
    index = NNDescent(x)
    neighbors = np.empty((num_pts, k), dtype=np.int)
    p_ij = np.empty((num_pts, k))
    for i, xi in enumerate(x):
        if verbose:
            print('Calculating probabilities: {cur}/{tot}'.format(
                cur=i+1, tot=num_pts), end='\r')
        nn, dists = index.query([xi], k+1)
        sigma = find_sigma(dists[0, 1:], k)
        neighbors[i] = nn[0, 1:]
        p_ij[i] = np.exp(- (dists[0, 1:] - dists[0, 1]) / sigma)
    row_indices = np.repeat(np.arange(num_pts), k)
    p = csr_matrix((p_ij.ravel(), (row_indices, neighbors.ravel())))
    return p + p.transpose() - (p.multiply(p.transpose()))

In [5]:
def pdiff(x):
    batch_size = x.shape[0]
    expanded = x.unsqueeze(1)
    tiled = torch.repeat_interleave(expanded, batch_size, dim=1)
    diffs = tiled - tiled.transpose(0, 1)  
    return diffs

In [6]:
def find_ab_params(spread, min_dist):
    """Fit a, b params for the differentiable curve used in lower
    dimensional fuzzy simplicial complex construction. We want the
    smooth curve (from a pre-defined family with simple gradient) that
    best matches an offset exponential decay.
    """

    def curve(x, a, b):
        return 1.0 / (1.0 + a * x ** (2 * b))

    xv = np.linspace(0, spread * 3, 300)
    yv = np.zeros(xv.shape)
    yv[xv < min_dist] = 1.0
    yv[xv >= min_dist] = np.exp(-(xv[xv >= min_dist] - min_dist) / spread)
    params, covar = curve_fit(curve, xv, yv)
    return params[0], params[1]

In [12]:
def dist_mat_squared(x):
    batch_size = x.shape[0]
    expanded = x.unsqueeze(1)
    tiled = torch.repeat_interleave(expanded, batch_size, dim=1)
    diffs = tiled - tiled.transpose(0, 1)
    sum_act = torch.sum(torch.pow(diffs,2), axis=2)    
    return sum_act

In [127]:
# more memory-efficient version of distmat
def dist_mat_squared_new(x):
    n = x.shape[0]
    distmat_cond = F.pdist(x)
    distmat = torch.zeros((n,n), device=x.device)
    a,b = torch.triu_indices(n, n, offset=1)
    distmat[[a,b]] = distmat_cond.pow(2)
    return distmat + distmat.T

In [212]:
foo = torch.tensor([[-1,-3],[-1,1],[1,5],[4,-1]], dtype=torch.float32, requires_grad=True)
states = [foo.clone().detach()]
for _ in range(100):
    bar = 1 / dist_mat_squared_new(foo).sum()
    bar.backward()
    with torch.no_grad():
        foo += foo.grad
    states.append(foo.clone().detach())

In [213]:
states

[tensor([[-1., -3.],
         [-1.,  1.],
         [ 1.,  5.],
         [ 4., -1.]]),
 tensor([[-0.9998, -2.9997],
         [-0.9998,  1.0000],
         [ 1.0000,  4.9996],
         [ 3.9997, -0.9999]]),
 tensor([[-0.9995, -2.9990],
         [-0.9995,  0.9999],
         [ 0.9999,  4.9987],
         [ 3.9991, -0.9996]]),
 tensor([[-0.9990, -2.9980],
         [-0.9990,  0.9997],
         [ 0.9999,  4.9975],
         [ 3.9982, -0.9992]]),
 tensor([[-0.9984, -2.9967],
         [-0.9984,  0.9995],
         [ 0.9998,  4.9958],
         [ 3.9970, -0.9986]]),
 tensor([[-0.9975, -2.9951],
         [-0.9975,  0.9993],
         [ 0.9996,  4.9937],
         [ 3.9954, -0.9979]]),
 tensor([[-0.9966, -2.9931],
         [-0.9966,  0.9990],
         [ 0.9995,  4.9912],
         [ 3.9936, -0.9971]]),
 tensor([[-0.9954, -2.9908],
         [-0.9954,  0.9987],
         [ 0.9993,  4.9882],
         [ 3.9915, -0.9961]]),
 tensor([[-0.9941, -2.9882],
         [-0.9941,  0.9983],
         [ 0.9992,  4.9849],
 

In [195]:
bar = dist_mat_squared_new(foo).sum()

In [196]:
bar.backward()

In [190]:
foo.grad

tensor([[ -400.3861,    47.3844, -1921.0607,  ...,  -362.8801,  -951.4847,
          -382.1129],
        [ 1370.8921, -1097.1067, -1099.6359,  ...,  -404.0282,  -260.7700,
          1126.6843],
        [ -278.9686,  1723.1650, -1009.9611,  ...,  1556.6245,  1477.4880,
         -1001.4337],
        ...,
        [ 1258.7163,   886.4594,   506.8771,  ...,  -253.6815,  1898.3467,
          -921.6090],
        [-1330.0966,  1862.8799, -1584.3247,  ...,  1622.6505,    51.9634,
         -1540.7065],
        [-1740.8436,   995.6321,  -321.3471,  ...,  1029.9807,  1579.5074,
          -137.0587]], device='cuda:0')

In [197]:
foo.grad

tensor([[ -400.3863,    47.3844, -1921.0609,  ...,  -362.8799,  -951.4847,
          -382.1129],
        [ 1370.8921, -1097.1067, -1099.6355,  ...,  -404.0281,  -260.7701,
          1126.6844],
        [ -278.9687,  1723.1642, -1009.9618,  ...,  1556.6246,  1477.4889,
         -1001.4344],
        ...,
        [ 1258.7168,   886.4589,   506.8768,  ...,  -253.6816,  1898.3466,
          -921.6089],
        [-1330.0967,  1862.8804, -1584.3248,  ...,  1622.6510,    51.9635,
         -1540.7072],
        [-1740.8440,   995.6320,  -321.3473,  ...,  1029.9811,  1579.5079,
          -137.0588]], device='cuda:0')

In [ ]:
def q_ij(x, a, b):
    dists = dist_mat_squared(x)
    dists.fill_diagonal_(1.)
    q = torch.pow(1 + a * torch.pow(dists, b), -1)
    q.fill_diagonal_(0.)
    return q

In [ ]:
def submatrix(m, indices):
    dim = len(indices)
    indices = np.array(np.meshgrid(indices, indices)).T.reshape(-1,2).T
    return torch.tensor(m[indices[0], indices[1]].reshape(dim, dim))

In [ ]:
def umap_loss(p, q, eps=1.0e-7):
    eps = torch.tensor(eps, dtype=p.dtype)
    l_a = torch.mul(p, torch.log(p + eps) - torch.log(q + eps))
    l_b = torch.mul(1 - p, torch.log(1 - p + eps) - torch.log(1 - q + eps))
    loss_mat = l_a #+ l_b
    loss_mat.fill_diagonal_(0.)
    return torch.sum(loss_mat)

In [ ]:
class Parametric_UMAP(nn.Module):
    
    def __init__(self, input_dim, output_dim, knn, min_dist,
                 spread=1.0,
                 hidden_layer_dims=None,
                 seed=None,
                 use_cuda=False):
        super().__init__()
        
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.knn = knn
        self.min_dist = min_dist
        self.spread = spread
        
        self.a, self.b = find_ab_params(self.spread, self.min_dist)
        
        self.use_cuda = use_cuda
        
        if seed is not None:
            torch.manual_seed(seed)
            np.random.seed(seed)
        
        # If no layers provided, use the same architecture as van der maaten 2009 paper
        if hidden_layer_dims is None:
            hidden_layer_dims = [500, 500, 2000]
        
        self.layers = nn.ModuleList()
        
        cur_dim = input_dim
        for hdim in hidden_layer_dims:
            self.layers.append(nn.Linear(cur_dim, hdim))
            cur_dim = hdim
        self.layers.append(nn.Linear(cur_dim, output_dim))
        
        if self.use_cuda:
            self.cuda()
        
    def forward(self, x):
        for layer in self.layers[:-1]:
            # x = torch.sigmoid(layer(x))
            x = F.softplus(layer(x))
        out = self.layers[-1](x)
        return out
    
    def pretrain(self, training_data,
            epochs=10,
            verbose=False,
            batch_size=500,
            learning_rate=0.01):
        if verbose:
            print('Calculating PCA')
        pca = torch.tensor(PCA(n_components=2).fit_transform(training_data), dtype=training_data.dtype)
        
        dataset = torch.utils.data.TensorDataset(training_data, pca)
        dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)
        optim = torch.optim.Adam(self.parameters(), lr=learning_rate)
        criterion = nn.MSELoss()
        
        if verbose:
            print('{time}: Beginning pretraining for {epochs} epochs'.format(
                time=datetime.datetime.now(),
                epochs=epochs))
        
        for epoch in range(epochs):
            running_loss = 0
            for batch, data in enumerate(dataloader):
                
                features, targets = data
                    
                if self.use_cuda:
                    features = features.cuda()
                    targets = targets.cuda()
                    
                optim.zero_grad()
                
                loss = criterion(self(features), targets)
                
                loss.backward()
                optim.step()
                    
                running_loss += loss.item()
                
            if verbose:
                print('{time}: Loss after epoch {ep}: {rloss}'.format(
                    time=datetime.datetime.now(),
                    ep=epoch,
                    rloss=running_loss))

        if verbose:
            print('{time}: Finished pretraining'.format(
                time=datetime.datetime.now()))
        
    def fit(self, training_data,
            p_ij=None,
            pretrain=False,
            epochs=10,
            verbose=False,
            optimizer=torch.optim.Adam,
            batch_size=500,
            learning_rate=0.01):
        
        assert training_data.shape[1] == self.input_dim, "Input training data must be same shape as training `num_inputs`"
        
        self.p_ij = p_ij
        self._epochs = epochs
        
        if pretrain:
            self.pretrain(training_data, epochs=5, verbose=verbose, batch_size=batch_size)
            
        if self.p_ij is None:
            self.p_ij = p_ij_sym(training_data.numpy(), self.knn, verbose=verbose)
            
        dataset = torch.utils.data.TensorDataset(training_data, torch.arange(training_data.shape[0]))
        dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)
        optim = optimizer(self.parameters(), lr=learning_rate)
        
        if verbose:
            print('{time}: Beginning training for {epochs} epochs'.format(
                time=datetime.datetime.now(),
                epochs=epochs))
        
        for epoch in range(epochs):
            running_loss = 0
            for batch, data in enumerate(dataloader):
                
                features, indices = data
                
                p = submatrix(self.p_ij, indices.numpy())
                    
                if self.use_cuda:
                    features = features.cuda()
                    p = p.cuda()
                    
                optim.zero_grad()
                
                q = q_ij(self(features), self.a, self.b)
                loss = umap_loss(p, q)
                
                loss.backward()
                optim.step()
                    
                running_loss += loss.item()
                
            if verbose:
                print('{time}: Loss after epoch {ep}: {rloss}'.format(
                    time=datetime.datetime.now(),
                    ep=epoch+1,
                    rloss=running_loss))

        if verbose:
            print('{time}: Finished training'.format(
                time=datetime.datetime.now()))
            
    def test(self, training_data,
            p_ij=None,
            optimizer=torch.optim.Adam,
            batch_size=500,
            learning_rate=0.01):
        
        assert training_data.shape[1] == self.input_dim, "Input training data must be same shape as training `num_inputs`"
        
        self.p_ij = p_ij
            
        if self.p_ij is None:
            self.p_ij = p_ij_sym(training_data.numpy(), self.knn, verbose=True)
            
        dataset = torch.utils.data.TensorDataset(training_data, torch.arange(training_data.shape[0]))
        dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)
        optim = optimizer(self.parameters(), lr=learning_rate)
        
        for epoch in range(5):
            running_loss = 0
            for batch, data in enumerate(dataloader):
                
                features, indices = data
                
                p = submatrix(self.p_ij, indices.numpy())
                    
                if self.use_cuda:
                    features = features.cuda()
                    p = p.cuda()
                    
                optim.zero_grad()
                
                q = q_ij(self(features), self.a, self.b)
                loss = umap_loss(p, q)
                
                return self(features), p, q, loss
                
                loss.backward()
                optim.step()
                    
                running_loss += loss.item()

-----------------------

In [ ]:
from torchvision.datasets import MNIST
import torchvision.transforms as transforms

In [ ]:
mnist = MNIST(
    './data',
    train=True,
    download=True,
    transform=transforms.ToTensor()
)

In [ ]:
testdata = mnist.data.reshape(-1, 28*28) / 255.

In [ ]:
foo = Parametric_UMAP(28*28, 2, 100, 0.01, use_cuda=True, hidden_layer_dims=[300,100])

In [ ]:
p_precalc = foo.p_ij

In [ ]:
foo.fit(testdata[:20000], p_ij=p_precalc, batch_size=500, epochs=20, learning_rate=0.1, pretrain=False, verbose=True)

In [ ]:
bar = foo(testdata[:10000].cuda()).cpu().detach().numpy()

In [ ]:
from matplotlib import pyplot as plt
import matplotlib.patches as mpatches

In [ ]:
fig = plt.figure(figsize=(20, 10))
ax = fig.add_subplot(111)
colors = [plt.cm.tab10.colors[i] for i in mnist.targets[:10000]]
ax.scatter(bar[:,0],bar[:,1],c=colors, s=2)
recs = []
for i in range(0,10):
    recs.append(mpatches.Rectangle((0,0),1,1,fc=plt.cm.tab10.colors[i]))
ax.legend(recs,list(range(10)),loc=2)

In [ ]:
foof, foop, fooq, fool = foo.test(testdata[:20000], p_ij=p_precalc, batch_size=500, learning_rate=0.1)

In [ ]:
foop.min()

In [ ]:
a = foop.detach().cpu()

In [ ]:
a

In [ ]:
b = foof.clone().detach().cpu().requires_grad_(True)

In [ ]:
c = q_ij(b, 1.93, 0.79)

In [ ]:
c

In [ ]:
(a/c).fill_diagonal_(0.).min()

In [ ]:
b.grad

In [ ]:
a = torch.tensor([[0.5, 0.6], [0.7, 0.3]])
b = torch.tensor([[0.1, 0.2], [0.4, 0.3]], requires_grad=True)
c = q_ij(b, 1.93, 0.79)

In [ ]:
umap_loss(a, c).backward()

In [ ]:
b.grad